# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          keys961 - Green House
paginate:       5
baseurl:        ""
url:            "https://keys961.github.io/"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         keys961
  url:          http://github.com/keys961
  email:        keys961@hotmail.com

# Custom vars
version:        3.4.1
github:
  repo:         http://github.com/keys961

# Gems
gems:
  - jekyll-paginate
